### ISSUE TITLE
Setup redux for the react client

### ISSUE THREAD

**Issue by krishnagopinath** [Matterwiki/Matterwiki#114]
The code is becoming a little off hand with `setState` currently. Pulling in a state management lib like Redux or Freactal would be fanstastic for the code base.

**Comment by spaceraccoon** [comment]
I can handle this actually - been using redux a ton :)

**Comment by krishnagopinath** [comment]
Awesome :D

Talk to @nshntarora about this. I'd say you hold off on this till #103 and #104 get merged. I wouldn't want to be stuck with our old API.

**Comment by spaceraccoon** [comment]
For sure. I'm still wrapping up some stuff this week but then I can start
mapping out the state tree.

**Comment by krishnagopinath** [comment]
Perfect! Now that you've redux a lot, why not check this out? 

https://github.com/FormidableLabs/freactal/

I kinda like how the opinions folks had when they built this out. [Here's the introductory blog post](https://formidable.com/blog/2017/infinite-state-composition-with-freactal/). If this resonates with your (and @nshntarora's) mind ethos, why not integrate this into Matterwiki instead of using redux? 

But hey, just an opinion! 😉

**Comment by spaceraccoon** [comment]
Awesome, I'll take a look and play around!

**Comment by nshntarora** [comment]
Awesome @spaceraccoon 😃 
Once you have the state map ready, I'd say, why don't you go for the initial set up too. Just install and put everything in the right place. You have worked with it, your setup could handle issues and solve for mistakes redux beginners like me would make.
Then, when we have the initial setup ready, we divide the state tree among ourselves and start implementing.

What do you think?

**Comment by spaceraccoon** [comment]
Sounds good!

**Comment by krishnagopinath** [comment]
@nshntarora as you work on redux, I would suggest not storing editorState in the state store.This is ideally local state and that will get destroyed quick quickly. Another reason is that the editor area could be independent of redux, so in the future (I know, YAGNI), if we need to pull it out as a separate dependency via lerna/yarn workspaces or something, it'd be easy to achieve.
