### ISSUE TITLE
Comparison with jingo

### ISSUE THREAD

**Issue by dandv** [Matterwiki/Matterwiki#12]
How does this wiki engine compare to the more popular [jingo](https://github.com/claudioc/jingo) by @claudioc? Do you have a [prior art](https://slides.com/dandv/prior-art/) article?

**Comment by nshntarora** [comment]
I did look at Jingo, when I was building Matterwiki. It's a great project.
With Matterwiki, I wanted to improve the installation for non-tech people (bring it down to just one command/form in the future) and make it more user friendly (in terms of writing). Also, give them the ability to completely customize their wiki from their dashboard. Plus, integrations using the API.
Think of jingo as Octopress and Matterwiki as Wordpress.

No, I don't have a prior art page as of now.
Checked the video. Completely agree. Adding it ASAP. :+1: 

Thanks :smile:

**Comment by nshntarora** [comment]
Added :+1:
