### ISSUE TITLE
Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by DBocksteger** [Matterwiki/Matterwiki#17]
Hi there,

I've set up a fresh Ubuntu 16.04 server with npm version 3.5.2 and nodes 4.2.6.

## Error
```
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```
### Log
I've also attached the nom-log from the matter wiki directory.
[npm-debug.log.zip](https://github.com/Matterwiki/Matterwiki/files/709328/npm-debug.log.zip)

**Comment by nshntarora** [comment]
Please try again after updating your `npm` package to the latest version (4.0 or later).
1. Run `npm install -g npm` or first uninstall `npm` and then run `sudo apt-get install npm`
2. Try `npm install` again.

Let me know if the problem persists.

**Comment by DBocksteger** [comment]
@nshntarora the Problem is I can't get my server to install a newer version than the installed one.

```
apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (3.5.2-0ubuntu4).
```

Also ran `apt-get update` and `apt-get upgrad`

**Comment by nshntarora** [comment]
First uninstall npm using `apt-get remove`.
Then try installing through `curl`
Command: `curl -L https://www.npmjs.com/install.sh | sh`

**Comment by DBocksteger** [comment]
@nshntarora works now. but...

```
node index
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Client._driver (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/knex/lib/dialects/sqlite3/index.js:65:12)
    at Client.initializeDriver (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/knex/lib/client.js:211:26)
    at Client (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/knex/lib/client.js:92:10)
    at Client_SQLite3 (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/knex/lib/dialects/sqlite3/index.js:51:23)
    at new Client (/var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki/node_modules/knex/lib/util/make-client.js:24:18)
```

Do you also the reason why `node index` fails?

**Comment by nshntarora** [comment]
That is because when the `node-gyp` failed `sqlite` wasn't installed. After
the failure it exited and SQLite was left out.

a `npm install sqlite` should fix it.

Or, run `npm install` again

**Comment by nshntarora** [comment]
That is because when the `node-gyp` failed `sqlite` wasn't installed. After
the failure it exited and SQLite was left out.

`npm install sqlite3` should fix it.

Or, run `npm install` again

**Comment by aniljava** [comment]
Environment:

    /root/Desktop/matterwiki :: # node --version
    v7.2.1
    /root/Desktop/matterwiki :: # npm --version
    4.1.1
    /root/Desktop/matterwiki :: # 

Used `curl -L https://www.npmjs.com/install.sh | sh` to install npm.

I am getting similar problem:

    /root/Desktop/matterwiki :: # npm install
    
    > bcrypt@0.8.7 install /root/Desktop/matterwiki/node_modules/bcrypt
    > node-gyp rebuild
    
    Traceback (most recent call last):
      File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
        import gyp
      File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
        import gyp.input
      File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
        from compiler.ast import Const
    ImportError: No module named ast
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Linux 4.4.0-47-generic
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /root/Desktop/matterwiki/node_modules/bcrypt
    gyp ERR! node -v v7.2.1
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok 
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm ERR! Linux 4.4.0-47-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v7.2.1
    npm ERR! npm  v4.1.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the bcrypt package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs bcrypt
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls bcrypt
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /root/Desktop/matterwiki/npm-debug.log

**Comment by aniljava** [comment]
Solved. Please leave issue Leave closed. 
On my case, the PYTHONPATH was pointing to a other lib containing compiler instead of compiler module expected by gyp.

**Comment by emmymbaraga** [comment]
![image](https://user-images.githubusercontent.com/31252004/101613654-b11a9b80-3a14-11eb-861d-3b5382b0a266.png)
i have the same problem when I run meteor npm install command on window 10
