### ISSUE TITLE
Feature request: Live demo

### ISSUE THREAD

**Issue by madsnedergaard** [Matterwiki/Matterwiki#20]
Creating a live demo that can be interacted with at first, would definitely help people getting to know the platform before installation.

Might even be some sort of read-only if easier/possible, just to give the reader an idea of how it all works.

This issue has been mentioned on both Reddit and Producthunt, just thought I would add it properly here as well to help track it :)

**Comment by Agezao** [comment]
I've added the matterwiki main repo at a free dyno on Heroku. It can be accessed via: https://matterwiki.herokuapp.com/

I've updated the README.md with this reference too, PR at:
https://github.com/Matterwiki/Matterwiki/pull/27

Hope this help :-)

**Comment by madsnedergaard** [comment]
Awesome, that's perfect! Link could/should be added to matterwiki.com too :)

**Comment by sujaykundu777** [comment]
Will be added Soon :) :+1:
