### ISSUE TITLE
Default user/password

### ISSUE THREAD

**Issue by Fastidious** [Matterwiki/Matterwiki#26]
What is the default user and password? I am assuming there is one, as going to localhost:5000/#/setup presents me with a login screen, nothing else.

**Comment by Fastidious** [comment]
OK, managed to create (had to stop/start the application to be presented the setup screen). After adding an admin account, it does nothing at the login screen (no errors, but it isn't logging me in). Stopped/started the application to no avail. Am I missing something?

**Comment by Dan458** [comment]
I had the same issue are you using Safari? 

I was about to create an issue but it only occurs for me when using Safari to try and login / create an account. Switching to Chrome the creation of the account and login works as expected.

Thanks
Dan

**Comment by sujaykundu777** [comment]
Are you trying it in the incognito mode of Safari? because Matterwiki uses
localStorage to store your session and that is known to have problems in
Safari in incognito mode.

**Comment by Dan458** [comment]
Nope. Plain old Safari nothing fancy apart from a 1password extension.

Version 10.0.2 (12602.3.12.0.1)

**Comment by Fastidious** [comment]
Confirmed. Works with Chrome, not with Safari. We seem to have found a bug.

**Comment by chrisDeFouRire** [comment]
Safari is lacking the fetch API... A polyfill should be used I guess (https://github.com/github/fetch)

**Comment by chrisDeFouRire** [comment]
should be fixed with https://github.com/Matterwiki/Matterwiki/pull/34

**Comment by Dan458** [comment]
Just be notified on the merge. Pulled and tested. Login now working on Safari. Good job :)
