### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by miherlosev** [Matterwiki/Matterwiki#28]
Matterwiki is a complex application.
I propose to write e2e tests and setup CI on `travis` or `appveyor`.
I can do this using [testcafe](https://github.com/DevExpress/testcafe).
What do you think about it?

**Comment by sujaykundu777** [comment]
That will be Perfect. :+1:

**Comment by miherlosev** [comment]
Ok. Tomorrow I will start to do this

**Comment by miherlosev** [comment]
Done in https://github.com/Matterwiki/Matterwiki/pull/57
