### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by westwick** [Matterwiki/Matterwiki#31]
I didn't see this in the readme and I think it could be useful to others. I followed your setup instructions on a fresh Ubuntu box, and besides a few dependency problems (the sqlite version was incompatible with the node version), the only real problem I have is that the server doesn't stay "online". I don't know if you have a recommendation for this but if you have any tips on how to get this to stay up I'd love to hear it. I don't know if maybe I did something wrong, maybe I need to set up some kind of uptime daemon, or what, but I constantly have to ssh into the box and run `node index` to start the server up again. Also, it defaulted to port 5000 and I couldn't find in the readme where to change this default port. Any tips for these 2 issues?

**Comment by westwick** [comment]
Also 2 other things. 

1) I deleted the default entry/topic but it stays "cached" on the home screen, resulting in 'cannot read property "related" of null' error.

2) What is the sorting algorithm for posts? It seems like it's just by whatever was created most recently. It'd be great to have it sort by whatever was UPDATED most recently, or to be able to set a specific sort order on them maybe? (Should I open a separate ticket for this feature request?)

BTW also want to mention love the simplicity of this project and the nice UI, maybe I will find more time and try to contribute myself :)

**Comment by Dan458** [comment]
To answer your first two questions.

In index.js the last section:

app.listen(5000 || process.env.PORT, function(){
  console.log("The magic is happening on port 5000");

You can change the port there.

I use pm2 to keep my application live :)

Hope it helps 

Dan

**Comment by westwick** [comment]
Thanks that was super easy :)

**Comment by BanshaTang** [comment]
@Dan458 Hello, when I try to use pm2 to keep it live, the webpage shows "Pool is destroyed."

I use pm2 to run index.js file, do I have to run other files? 

Thank you

**Comment by Dan458** [comment]
@BanshaTang all i run is pm2 start index.js --name 'app name' and it all works ok. I haven't connected to a database.

Thanks
Dan

**Comment by nshntarora** [comment]
@BanshaTang The "Pool is destroyed" error occurs when the app faces some trouble connecting/interacting with the database. Does the user running the app has write access to the `db` directory?
Please check permissions and let me know.
