### ISSUE TITLE
Use PM2 to keep it running shows "Pool is destroyed"

### ISSUE THREAD

**Issue by BanshaTang** [Matterwiki/Matterwiki#32]
Matterwiki runs well if I "npm start".

But when I try to keep it running with PM2, Matterwiki shows "Pool is destroyed".

I just use PM2 to run the index.js file, do I need to run other files?

**Comment by nshntarora** [comment]
@BanshaTang The "Pool is destroyed" error occurs when the app faces some trouble connecting/interacting with the database. Does the user running the app has write access to the `db` directory?
Try running `pm2` with `sudo` and see if it works.
Please check permissions and let me know.

Issue first mentioned in #31

**Comment by nshntarora** [comment]
Closing issue due to no response.
