### ISSUE TITLE
Nothing happens after node index

### ISSUE THREAD

**Issue by DBocksteger** [Matterwiki/Matterwiki#36]
I've run the following but now nothing happens anymore.

```
npm run build
> Matterwiki@0.1.0 build /var/www/vhosts/fachinformatiker-wiki.de/httpdocs/matterwiki
> webpack -p
> Hash: 01c87c3d8a7aa4a49157
> Version: webpack 1.13.2
> Time: 14783ms
    Asset    Size  Chunks             Chunk Names
> bundle.js  369 kB       0  [emitted]  main
    + 262 hidden modules
node index
> The magic is happening on port 5000
```

Calling my url turns out in "403 Forbidden"

**Comment by nshntarora** [comment]
The 403 error occurs because the visitor doesn't have access to view the files [read more](https://en.wikipedia.org/wiki/HTTP_403).
Check permissions of your `client` directory and its subdirectories. Give read access to all user groups.

Let me know if that fixes the issue :smile:

**Comment by DBocksteger** [comment]
Changed it for testing to 777 for /matterwiki... nothing changed? :o

**Comment by nshntarora** [comment]
Can you share your `npm-debug.log`?

**Comment by nshntarora** [comment]
Closing due to no response from the issuer.
If you're still facing this issue please re-open.

:smile:
