### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by k1ngf15h3r** [Matterwiki/Matterwiki#37]
Are there any plans for translation or can I make translations for my own?

Would like to use matterwiki in german ...

**Comment by nshntarora** [comment]
As of now there are no plans of translations. For now, the focus is on launching a stable release that doesn't break and handles everything.
Though we may go for translations in the future.

Would love it if you could write the translations and contribute it here to the main repo :smile:

**Comment by k1ngf15h3r** [comment]
Is there a file from where the texts came from or they all hard coded?

Am 19.01.2017 2:58 nachm. schrieb "Nishant Arora" <notifications@github.com

**Comment by nshntarora** [comment]
They're all hard coded. Didn't think of translations while building this.
But yeah, if you're going for translations you'll have to create a separate JSON file which has all the strings and modify the client code to use the respective string from that JSON file.
For users language could be selected by editing the `config.js` file.

This will also help us translating Matterwiki in other languages in the future.

**Comment by k1ngf15h3r** [comment]
Okay I will try to make a json file for german translations. maybe you could help after that to integrate this ;)

**Comment by nshntarora** [comment]
Yes, for sure. Eagerly waiting.

**Comment by k1ngf15h3r** [comment]
Can you tell me in which files the text is stored. I never worked with nodejs before :-D

**Comment by MinweiShen** [comment]
@k1ngf15h3r They are all hardcoded in files. Not read from one particular file.

**Comment by k1ngf15h3r** [comment]
I know :) I mean can you tell me in which folders are the files which
contains the frontend code and texts? ;)

Am 20.01.2017 05:40 schrieb "Minwei Shen" <notifications@github.com>:

**Comment by MinweiShen** [comment]
@k1ngf15h3r They should be in the client/app/components folder, *.jsx files

**Comment by k1ngf15h3r** [comment]
Can you check if attached json goes in the right direction?
[de.json.zip](https://github.com/Matterwiki/Matterwiki/files/720272/de.json.zip)

**Comment by MinweiShen** [comment]
what about making the values an object? Like:

{
   de: 'blablabla',
   en: 'help content',
   zh: 'blablabla'
}

I am also interested in translating this.

**Comment by k1ngf15h3r** [comment]
Sure this would be better. First time I wrote a json file today :-D will
change it tomorrow

Am 20.01.2017 22:06 schrieb "Minwei Shen" <notifications@github.com>:

**Comment by k1ngf15h3r** [comment]
Checkout the new language.json. First I made objects for the sites, then for the objects in the site and last objects for the languages
[language.zip](https://github.com/Matterwiki/Matterwiki/files/721042/language.zip)

**Comment by nshntarora** [comment]
@k1ngf15h3r Apologies for the late response. Been a little busy.
Great work.
Though this would be the format I'd prefer.

```
{
    "de": {
             "no_articles": "Es gibt keine Artikel zu diesem Thema"
              ...
             },
    "en": {
             "no_articles": "There are no articles to this Topic"
             }
             ...
}
```

The user then just has to change the default language object in `config.json`.
```
{
    "language": "de"
}
```

The in the client we import the config life and the language's object for the selected language.
I believe this would be a much cleaner way to do it.

Would love to know what you think @krishnagopinath

**Comment by nshntarora** [comment]
@MinweiShen Awesome! Which language will you be translating in?

**Comment by MinweiShen** [comment]
@nshntarora I can translate it to Chinese.

**Comment by nshntarora** [comment]
@MinweiShen Great! Let's begin then. Let me know if you need any help :smile:

**Comment by nshntarora** [comment]
@MinweiShen and @k1ngf15h3r if you need some personal help you can always email me at `na.nishantarora at gmail dot com`

**Comment by k1ngf15h3r** [comment]
I will make translation for German later. The format you posted is exactly what we need. I am a noob in json and node.js but giving my best to translate all needed parts :)

**Comment by krishnagopinath** [comment]
Seems to be the way to go ahead, @nshntarora !

**Comment by k1ngf15h3r** [comment]
This is my language.json for the admin.jsx so far. I think I have all parts in it that could be translated ...
```
{
    "de": {
            "add_user": "Benutzer hinzufügen",
            "add_topic": "Thema hinzufügen",
            "edit": "bearbeiten",
            "delete": "löschen",
            "name": "Name",
            "about": "Über",
            "description": "Beschreibung",
            "email": "E-Mail",
            "password": "Passwort",
            "user_added": "Benutzer wurde erstellt",
            "user_deleted": "Benutzer wurde gelöscht",
            "topic_added": "Thema wurde erstellt",
            "topic_deleted": "Thema wurde gelöscht"
    },
    "en": {
            "add_user": "Add User",
            "add_topic": "Add Topic",
            "edit": "Edit",
            "delete": "Delete",
            "name": "Name",
            "about": "About",
            "description": "Description",
            "email": "Email",
            "password": "Password",
            "user_added": "User has been added",
            "user_deleted": "User has been deleted",
            "topic_added": "Topic has been added",
            "topic_deleted": "Topic has been deleted"
    }
}
```

**Comment by c-cho** [comment]
Hi @k1ngf15h3r @MinweiShen Why not try to use locale formatted in "[ISO639]-[ISO3166]" like "de-DE".
It will make the project more flexible for further translation.

**Comment by k1ngf15h3r** [comment]
@c-cho sure that is a good idea. Will change this

**Comment by sebki** [comment]
I could help with the German translation, maybe we split up the components between us @k1ngf15h3r? Am also very much interested in this project and would love to use it in my team.

**Comment by k1ngf15h3r** [comment]
@sebki nice work will change my admin.l10n.json to your format and make a pull request too. Will try to translate more files later. Had a 12 hours day so might take some time ;)

**Comment by k1ngf15h3r** [comment]
added the l10n files for the first 5 components, I think we are on a good way to get translation going to be released :smiley:

**Comment by nshntarora** [comment]
@sebki and @k1ngf15h3r Great job guys! Just looked at the pull requests. I'd suggest both of you make a separate branch called `german-translation` and target your pull requests to that.
Later, once all strings are translated and are added to the components, we'll merge that branch with `master`.

:+1:

**Comment by k1ngf15h3r** [comment]
replaced PR #53 with new PR #55 with branch german-translation
