### ISSUE TITLE
Import from another Wiki

### ISSUE THREAD

**Issue by mgohin** [Matterwiki/Matterwiki#39]
Hi,

looks nice and promising, but we are using [DokuWiki](https://www.dokuwiki.org).

Any chance to have an import function ?

**Comment by nshntarora** [comment]
Not in the near future. But, yes got it on our roadmap.
[Check it out here](https://trello.com/b/OktmtAve/feature-roadmap)

**Comment by mgohin** [comment]
Thanks.

We can't switch because of this missing feature.

I'll watch this wiki app ;)

**Comment by krishnagopinath** [comment]
@mgohin going to re-open this issue for tracking. I hope you don't mind ;)

**Comment by mgohin** [comment]
Hoooo I don't mind at all, we would be glad to switch from DokuWiki to Matterwiki 👍

**Comment by mgohin** [comment]
Any news ?

**Comment by mgohin** [comment]
Any updates ?
