### ISSUE TITLE
Writing an ampersand (&) breaks the document structure

### ISSUE THREAD

**Issue by alexgleason** [Matterwiki/Matterwiki#51]
If I create a document that includes an ampersand character, the copy will be truncated at that point and the rest won't be saved.

**Comment by krishnagopinath** [comment]
Do you mean in the title, @alexgleason ?

**Comment by alexgleason** [comment]
@krishnagopinath Nope, the content. If I create a new page and write

>this is a test to see if writing an & ampersand will work

then save, the resulting page has this text in the body

>this is a test to see if writing an

**Comment by krishnagopinath** [comment]
Funny, the content seems to be fine at my end. :(

It's the title that seems to have this problem, something that #49 fixes, that's yet to be merged. #33 fixed the content problem. Are you sure you're using the latest version?

**Comment by alexgleason** [comment]
@krishnagopinath I'm using a version updated 5 days ago via this Docker image: https://hub.docker.com/r/furiousgeorge/matterwiki/

**Comment by nshntarora** [comment]
Fixed. In the latest commits.

Let me know if you're still facing this :smile:

**Comment by alexgleason** [comment]
Thanks!

**Comment by prime-ralph** [comment]
This still happens with the topic names. If a topic has been added or updated with an &, it will be truncated up to the last character before the ampersand.

**Comment by nshntarora** [comment]
Hi @prime-ralph 

Just fixed it. Please pull the latest changes from master.
