### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by myklam** [Matterwiki/Matterwiki#54]
The font is very pretty for the most part, but the number one is far too similar to a capital i.

**Comment by nshntarora** [comment]
Thankyou for pointing that out. Started looking into alternative fonts.

**Comment by calebsylvest** [comment]
I'd could be interested in helping on the type & design front. I was already thinking of making styling changes for personal use. Here's a rough work-in-progress I threw together.

@nshntarora is this something you would like help with? I'm not a programmer, but design and front-end styles are my specialty, so this is the best way I could contribute.

_WIP Example:_

![matterwiki-design-example](https://cloud.githubusercontent.com/assets/4457883/22479481/8abbded4-e7b3-11e6-80fd-aae085f63136.png)

**Comment by nshntarora** [comment]
@calebsylvest Love it. Let's get it implemented! You've got mail :mailbox_with_mail:

**Comment by nshntarora** [comment]
The body font is now changed from Vollkorn to Merriweather :+1:
