### ISSUE TITLE
installing fail on ubuntu server

### ISSUE THREAD

**Issue by misaki5960x** [Matterwiki/Matterwiki#58]
Hi, 

I'm new to use vps to run project. I really like how matterwiki looks. XD

When I run npm run build.
Below is my problems.

`
co@ubuntu:~/matterwiki$ npm run build

> Matterwiki@0.1.0 build /home/connor/matterwiki
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors

sh: 1: cross-env: not found

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! Matterwiki@0.1.0 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the Matterwiki@0.1.0 build script 'cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Matterwiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Matterwiki
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Matterwiki
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/co/matterwiki/npm-debug.log
`
I do have the node version 6.9.4
and npm version 4.1.2

Could you tell me what happen ?

Thank you

**Comment by krishnagopinath** [comment]
Hey, glad you like the design! :) 

Did you run `npm install` in the Matterwiki repository before `npm run build`?

**Comment by misaki5960x** [comment]
@krishnagopinath Hi,

I just followed the install instruction,

I'm sure I did npm install before npm run build.

I will try npm install again and give you the information that I received.

If you can record a video to present how to install matter wiki, I would be very appreciated.

**Comment by misaki5960x** [comment]
@krishnagopinath 
Hi, when I did npm install, 
there is a message says:

npm WARN deprecated node-uuid@1.4.7: use uuid module insteaddoParallel extract

**Comment by krishnagopinath** [comment]
Funny, seems to work here. Could you give me the npm-debug-log that is generated?

**Comment by misaki5960x** [comment]
Hi,
The attach file is the npm-debug-log.
Thank you :D


On Thu, Jan 26, 2017 at 10:20 AM, Krishna Gopinath <notifications@github.com

**Comment by misaki5960x** [comment]
I found another one inside matterwiki folder. (The previous one I send to
you was outside of matterwiki.)
This one is much smaller.

**Comment by misaki5960x** [comment]
@krishnagopinath 

I did npm install and then did npm run build again.
There is no error this time.
But when I did node index
This time something more interesting happened lol.



co@ubuntu-512mb-nyc1-01:~/matterwiki$ npm run build

> Matterwiki@0.1.0 build /home/co/matterwiki
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors
                                                  721868ms o1ms optimiz37ms emit
Hash: 19d1ec6588b1b27ab67b
Version: webpack 1.13.2
Time: 15088ms
        Asset    Size  Chunks             Chunk Names
    bundle.js  289 kB       0  [emitted]  main
bundle.js.map  2.5 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
       factory:1ms building:3ms = 4ms
    + 258 hidden modules


co@ubuntu-512mb-nyc1-01:~/matterwiki$ node index
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/co/matterwiki/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/co/matterwiki/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client._driver (/home/co/matterwiki/node_modules/knex/lib/dialects/sqlite3/index.js:65:12)
    at Client.initializeDriver (/home/co/matterwiki/node_modules/knex/lib/client.js:211:26)
    at Client (/home/co/matterwiki/node_modules/knex/lib/client.js:92:10)
    at Client_SQLite3 (/home/co/matterwiki/node_modules/knex/lib/dialects/sqlite3/index.js:51:23)


Does this mean something wrong with the database ?

**Comment by misaki5960x** [comment]
@krishnagopinath I might try other VPS (I'm using Digital Ocean) and try again.
Do you have any recommend VPS server ?
Thank you

**Comment by nshntarora** [comment]
@misaki5960x Sometimes when the build fails, the sqlite package is left out and is not installed. Installing the package using `npm install sqlite3` should fix the issue :smile:

**Comment by misaki5960x** [comment]
@nshntarora Thank you! I will try it!

**Comment by misaki5960x** [comment]
@nshntarora Thank you again! It was the problem with sqlite. I did npm install sqlite3 before I did npm install, and now my server can run matterwiki without any problem!
Thank you guys! @nshntarora @krishnagopinath
