### ISSUE TITLE
Invalid Date for every post

### ISSUE THREAD

**Issue by chrisDeFouRire** [Matterwiki/Matterwiki#60]
`Last updated on Invalid Date` shows below the post's name (in every view)

**Comment by nshntarora** [comment]
Could you please run `new Date().toDateString()` in your browser's console and tell me what it returns.
Also, please share your browser's name and version details.

**Comment by chrisDeFouRire** [comment]
You guessed right : Date().toDateString() returns 
```
TypeError: Date().toDateString is not a function. (In 'Date().toDateString()', 'Date().toDateString' is ```
on Safari/OSX... and it's working fine with Chrome/OSX

**Comment by nshntarora** [comment]
Fixed. :smile: 

The format of the timestamp is `2017-01-16 08:30:41` to make it compatible with Safari and others I had to add a `T` in the middle. While displaying I called a `.replace()` which should fix the issue.

Console test:
```
var date = "2017-01-16 08:30:41"
date = date.replace(' ','T');
new Date(date).toDateString()
```
