### ISSUE TITLE
Brand Update: Matterwiki Logo

### ISSUE THREAD

**Issue by calebsylvest** [Matterwiki/Matterwiki#69]
Hello friends,

I'm working on some design updates for the Matterwiki app in my spare-spare time. In the process, ended up working on a new brand/logo concept to go with the UI updates.

Wanted to share it with everyone for thoughts or input. @nshntarora hope you like it!

---

_Logo Usage_
![matterwiki-logo](https://cloud.githubusercontent.com/assets/4457883/22623114/e72c9e88-eb14-11e6-8470-b193857d5bfd.png)

_New Logo in Nav_
![image](https://cloud.githubusercontent.com/assets/4457883/22623132/69f16e70-eb15-11e6-9adf-616697de8858.png)

**Comment by krishnagopinath** [comment]
Whoa these look good! I personally love the single color logo :) looks clean and minimal!

**Comment by nshntarora** [comment]
Awesome! Love the design :smile: :+1: .

We'll have to think about color though.
I'm personally not a huge fan of Gradients. I believe, you cannot own it as you can own a solid color, and they're not evergreen, which is what I look for in logos.
(Just a belief. Point me in the right direction if I'm wrong)
Also, let's not consider our "Pink" to be the only option. If you think any other color would represent better, feel free to try it out.

Thought?

**Comment by krishnagopinath** [comment]
I'll close this for now. Will reopen when needed later. #110 tracks this as of now.

**Comment by captainhook** [comment]
This looks stunning, great work @calebsylvest 
Looking forward to implementation in 0.3.0 hopefully :)
