### ISSUE TITLE
Topics can't start with the same first word

### ISSUE THREAD

**Issue by Dan458** [Matterwiki/Matterwiki#76]
Hi,

If I create a Topic with name "Server Test" and then try to create another topic with name "Server Documents" the 2nd topic is not created. 

Please help in resolving.

Thanks
Dan

**Comment by nshntarora** [comment]
Hi, I'm not able to replicate your issue.
When did you install it?
Try doing a 'git pull` or a fresh clone and see if the issue exists.

**Comment by Dan458** [comment]
Meh, tried again today and its working fine. Im not sure what happened there.

Thanks for the help though.
Dan
