### ISSUE TITLE
build script failing

### ISSUE THREAD

**Issue by athahar** [Matterwiki/Matterwiki#77]
npm run build - failed with the following error. MacBookPro 

<replaced the folder path by ~/app in the logs below.>

`
> Matterwiki@0.1.0 build ~/app/Matterwiki
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors

/app/Matterwiki/node_modules/cross-env/dist/index.js:58
  var envVars = Object.assign({}, process.env);
                       ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at getCommandArgsAndEnvVars (/app/Matterwiki/node_modules/cross-env/dist/index.js:58:24)
    at crossEnv (/app/Matterwiki/node_modules/cross-env/dist/index.js:22:35)
    at Object.<anonymous> (/app/Matterwiki/node_modules/cross-env/bin/cross-env.js:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Matterwiki@0.1.0 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Matterwiki@0.1.0 build script.
npm ERR! This is most likely a problem with the Matterwiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors
npm ERR! You can get their info via:
npm ERR!     npm owner ls Matterwiki
npm ERR! There is likely additional logging output above.
`

**Comment by krishnagopinath** [comment]
Phew. That seems deadly. 

What version of `node` are you using?

**Comment by athahar** [comment]
v0.10.33

**Comment by athahar** [comment]
installed latest node - v6.9.5; all looks good :)

**Comment by athahar** [comment]
I haven't had updated my npm version from a long time. @krishnagopinath maybe a good time to put to have the supported node version in the README.

**Comment by krishnagopinath** [comment]
@athahar will do! Thanks for pointing it out. :)

**Comment by krishnagopinath** [comment]
Il leave this issue open so that we'll remember this.

**Comment by athahar** [comment]
well it doesnt work on ubuntu/digital ocean droplet 
Specs -> Linux magic 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux] 
Node -> v7.4.0

root@magic:/opt/wiki/matterwiki# npm start

> Matterwiki@0.1.0 start /opt/wiki/matterwiki
> npm run build && cross-env NODE_ENV=production node index.js


> Matterwiki@0.1.0 build /opt/wiki/matterwiki
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Matterwiki@0.1.0 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Matterwiki@0.1.0 build script 'cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors'.
npm ERR! This is most likely a problem with the Matterwiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors
npm ERR! You can get their info via:
npm ERR!     npm owner ls Matterwiki
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/wiki/matterwiki/npm-debug.log

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Matterwiki@0.1.0 start: `npm run build && cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Matterwiki@0.1.0 start script 'npm run build && cross-env NODE_ENV=production node index.js'.
npm ERR! This is most likely a problem with the Matterwiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cross-env NODE_ENV=production node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Matterwiki
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/wiki/matterwiki/npm-debug.log
root@magic:/opt/wiki/matterwiki#

**Comment by krishnagopinath** [comment]
Could you give us the `npm-debug` log?

**Comment by athahar** [comment]
Sorry didn't see your comment earlier. -> Sharing the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Matterwiki@0.1.0~prebuild: Matterwiki@0.1.0
6 silly lifecycle Matterwiki@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle Matterwiki@0.1.0~build: Matterwiki@0.1.0
8 verbose lifecycle Matterwiki@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle Matterwiki@0.1.0~build: PATH: /root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/bin/node-gyp-bin:/opt/wiki/matterwiki/node_modules/.bin:/root/.nvm/versions/node/v7.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle Matterwiki@0.1.0~build: CWD: /opt/wiki/matterwiki
11 silly lifecycle Matterwiki@0.1.0~build: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors' ]
12 silly lifecycle Matterwiki@0.1.0~build: Returned: code: 1  signal: null
13 info lifecycle Matterwiki@0.1.0~build: Failed to exec build script
14 verbose stack Error: Matterwiki@0.1.0 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Matterwiki@0.1.0
16 verbose cwd /opt/wiki/matterwiki
17 error Linux 3.13.0-68-generic
18 error argv "/root/.nvm/versions/node/v7.4.0/bin/node" "/root/.nvm/versions/node/v7.4.0/bin/npm" "run" "build"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error Matterwiki@0.1.0 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors`
22 error Exit status 1
23 error Failed at the Matterwiki@0.1.0 build script 'cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Matterwiki package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Matterwiki
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Matterwiki
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by athahar** [comment]
Checking if you guys have any pointers for me.

**Comment by nshntarora** [comment]
I'm not sure why is there a problem. Can you please email me personally, I'll help you set it up :smile: 
Email is `na.nishantarora at gmail.com`

**Comment by Swashed** [comment]
Hello, same issue as above, any fix? running ubuntu 16.04 latest nodejs on DO.

**Comment by nshntarora** [comment]
Hi @Swashed can you share your node and npm versions please?

**Comment by Herryyang** [comment]
@nshntarora My npm version is 4.41,node is 6.95

**Comment by krishnagopinath** [comment]
Been a while since this was raised. We're working a refactored release that should fix these issues
