### ISSUE TITLE
looses content after lines that end with whitespace

### ISSUE THREAD

**Issue by despairblue** [Matterwiki/Matterwiki#79]
![matterwiki](https://cloud.githubusercontent.com/assets/927609/23060721/41e60226-f4ff-11e6-8ad5-08c32b459865.gif)

The first time I added a single whitespace after the heading, everything after that is not send to the server.

The second time I did not add the whitespace and it worked as expected.

**Comment by nshntarora** [comment]
I'm not able to reproduce the issue. Are you on the latest `v0.2.0`?

**Comment by despairblue** [comment]
@nshntarora Good Point, I used [that](https://hub.docker.com/r/furiousgeorge/matterwiki/builds/) docker image, which was build a month ago. Seeing that 0.2 is just 5 days old I'm definitely on an old version. 

I'll check it out on 0.2 tomorrow.

**Comment by despairblue** [comment]
@nshntarora updated to 0.2 and the issue is gone. Thank you! 🙇
