### ISSUE TITLE
feature request: hosted solution 

### ISSUE THREAD

**Issue by siddharthkp** [Matterwiki/Matterwiki#8]
Not having the overhead of setup would be great.

**Comment by hong-duc** [comment]
How about a docker image, just pull it and run :smile:

**Comment by siddharthkp** [comment]
Umm, i should correct myself. 

Not just setup, but hosting it as well.

See related: https://github.com/Matterwiki/Matterwiki/issues/7

**Comment by calebsylvest** [comment]
An easy way to deploy to Heroku could be best. There are two ways to add heroku into the mix that could be useful:

1. **Manual**. Add clear documentation to the Readme for deploying the app to Heroku. Currently, IMO, deploying Matterwiki from a local build is tricky. I'm a moderately capable developer but couldn't get Matterwiki running on Heroku. So, a little more documentation around deploying to Heroku could be good.

2. **Deploy to Heroku Button**. To make a fully turnkey solution, building out a [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button) button could be the ticket. That would allow the "hosted solution" option mentioned above with very little setup.

Both options make me happy.

**Comment by spaceraccoon** [comment]
@calebsylvest , I managed to get it up on Heroku by cross-referencing the live demo branch. I'm happy to share with you my package.json (that's the only thing I modified).

**Comment by mandawan** [comment]
@spaceraccoon can you share your package.json with me too ? Did you specify a BuildPack in your app settings on heroku ?

A "deploy to heroku" button in the readme would be great though

**Comment by krishnagopinath** [comment]
#105

**Comment by ande1005** [comment]
Just in case anyone has tried deploying Matterwiki to Heroku and is pulling their hair out, here is my package.json file that's working:


{
  "name": "Matterwiki",
  "version": "0.2.3",
  "description": "A simple and beautiful wiki for teams",
  "main": "index.js",
  "scripts": {
    "build": "./node_modules/.bin/webpack --config ./webpack.config.prod.js --progress --profile --colors",
    "dev": "node index.js",
    "dev-testing": "cross-env TESTING=true node index.js",
    "start": "npm run build && node index.js",
    "testcafe": "testcafe chrome tests/e2e/tests/*.js --app \"npm run dev-testing\" --app-init-delay 10000",
    "test": "npm run build && npm run testcafe"
  },
  "bin": {
    "wiki": "./install.js"
  },
  "engines": {
    "node": "~0.12.0 || ^4.2.0 || ^6.5.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Matterwiki/Matterwiki.git"
  },
  "author": "Nishant Arora (@nshntarora)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Matterwiki/Matterwiki/issues"
  },
  "homepage": "http://matterwiki.com",
  "dependencies": {
    "babel-cli": "6.22.2",
    "babel-core": "6.22.1",
    "babel-loader": "6.2.10",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.22.0",
    "bcryptjs": "2.4.0",
    "body-parser": "1.15.2",
    "bookshelf": "0.10.0",
    "express": "4.14.0",
    "jsonwebtoken": "7.1.9",
    "knex": "0.11.10",
    "multer": "1.2.1",
    "pm2": "^3.0.0",
    "react": "15.3.0",
    "react-dom": "15.3.0",
    "react-hot-loader": "3.0.0-beta.6",
    "react-router": "2.8.1",
    "react-s-alert": "1.2.2",
    "sqlite3": "3.1.4",
    "webpack": "2.2.0",
    "webpack-dev-middleware": "1.9.0",
    "webpack-dev-server": "2.2.0",
    "webpack-hot-middleware": "2.15.0",
    "whatwg-fetch": "2.0.1"
  },
  "devDependencies": {
    "cross-env": "^3.1.4",
    "testcafe": "0.13.0"
  }
}
