### ISSUE TITLE
Building fails on FreeBSD

### ISSUE THREAD

**Issue by pentago** [Matterwiki/Matterwiki#80]
Here's the error log:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! FreeBSD 11.0-RELEASE-p2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/wiki/npm-debug.log
```

Full debug log: http://sprunge.us/BFIf

I'm not sure why script builds it's own sqlite3 package when all platforms have their own package?
Could anyone assist, please? Thanks in advance!

**Comment by pentago** [comment]
Note that this happens also when I choose MySQL as a DB driver. It still tries to setup sqlite3 for some  reason.

**Comment by nshntarora** [comment]
@pentago Thanks for pointing that out. `node-sqlite` uses prebuilt binaries for different operating systems and architectures. I don't think they one available for FreeBSD.

In this case you'll have to use `MySQL`, which you've already tried.

It is still trying to setup `Sqlite` as the library is still present in the `package.json` file.
Edit the `package.json` and remove `sqlite3` from the dependencies object, then try `npm install`

That should work. Let me know if it doesn't.

**Comment by pentago** [comment]
Thanks @nshntarora that worked. All good!
