### ISSUE TITLE
Passwords not being hashed when updating user details

### ISSUE THREAD

**Issue by prime-ralph** [Matterwiki/Matterwiki#83]
Updated user account details and was surprised to find that, instead of what I assume a bcrypt'ed password I found it sitting in the db in plaintext.
I'm using MySQL btw with the latest Matterwiki version on Ubuntu Xenial.

**Comment by nshntarora** [comment]
Hi @prime-ralph 
Thanks a lot for pointing this out. This is major. I'm really sorry for this mistake.
I'm to blame for it completely.

Fixed it in the latest commit. Please pull from master.

Also, I owe you a coffee now. Tweet me the next time you're in India :coffee: :smile:

**Comment by prime-ralph** [comment]
I just might take you up on that in the future. :) Thanks for the quick response!
