### ISSUE TITLE
feature request: knowledge  search 

### ISSUE THREAD

**Issue by devenbhooshan** [Matterwiki/Matterwiki#9]
It would be good if the knowledge is searchable.

**Comment by nshntarora** [comment]
Yes. I have it on the roadmap. Looking for the best way to implement it.
It'll be there for sure in the next version :+1:

**Comment by nshntarora** [comment]
@devenbhooshan If you have any suggestions on building it, please enlighten :smile:

**Comment by devenbhooshan** [comment]
Clientside you can use typehead and for backend there are many gems.
But it would be good if you can put a conversational agent for knowledge search like https://www.producthunt.com/posts/driftbot
The opportunities are endless 👍

**Comment by Rushmead** [comment]
Seeing as your using React, something like this for the client. https://github.com/fmoo/react-typeahead And backend wise it's just a case of having an end point such as /articles/search/:query and then have it search the database for titles that have that query in it. Very simple to implement :)

**Comment by nshntarora** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Knowledge Search](https://trello.com/c/AqDlKXk2/1-knowledge-search)

**Comment by nshntarora** [comment]
Just pushed to `knowledge-search` branch. Please pull and try it out.
Will be merging into `master` in a few days.

**Comment by swege** [comment]
Thanks! It works when I search for the title of an article, but the article body seems not to be indexed.

**Comment by nshntarora** [comment]
Thanks. Made the necessary changes. The body is also searched now :smile:
